array-methods - Matheus Sanders Montandon
msandersmontandon/m2-0723-code-solutions pull request #6
Opened 2023-07-20 00:04 UTC by msandersmontandon

https://github.com/msandersmontandon/m2-0723-code-solutions/assets/78445066/970be188-caad-485b-bc71-64790cab7e97

2023-07-21 04:01 UTC, TimelikeClosure requested changes

2023-07-21 04:01 UTC, TimelikeClosure commented on array-methods/for-each.js
> +values.forEach(() => {console.log(values[values.length - ++index])});
Close, but please only use callback parameters inside the callback function, not global variables.

2023-07-21 04:36 UTC, msandersmontandon commented on array-methods/for-each.js
> +values.forEach(() => {console.log(values[values.length - ++index])});
Yeah, it took me awhile to notice that the description of the parameters for the callback function was right in the top of the MDN document, xD. I've just made the changes.

2023-07-25 01:40 UTC, TimelikeClosure approved these changes

2023-07-25 02:14 UTC, merged